name: React


on:
  push:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: koteswararao-budati/portfoli

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
      - name: install dependencies
        run: |
          npm ci
      - name: test if present
        run: npm run test --if present
        env: 
          CI: false
      - name: running build
        run: npm run build
